### ISSUE TITLE
Implement browser open in natives

### ISSUE THREAD

**Issue by inikulin** [superroma/testcafe-browser-natives#7]
It should remove three args `path, cmd, pageUrl`

**Comment by AlexanderMoskovkin** [comment]
@inikulin I suggest the following API:
**`open(path, pageUrl, options)`**
`path` - (string) browser path
`pageUrl` - (string) page url
`options` - (object)[optional]
&nbsp;&nbsp;&nbsp;&nbsp;`{`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`newWindow` - (bool)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`cmdArgs` - (string)
&nbsp;&nbsp;&nbsp;&nbsp;`}`

Why `options` instead of `cmd`? If we use `cmd`, you should learn what cmd argument you should use to open a page in a new window for each browser(`-new-window` or `--new-window`) when using this module. More than that, on Mac you should use another syntax (not only the `-new-window` flag, but `open` command with flags).
We can use `options.cmdArgs` to send other cmd arguments.
What do you think?

**Comment by inikulin** [comment]
Why we need `newWindow` flag in `options`?

**Comment by AlexanderMoskovkin** [comment]
Do you mean 'why we need `newWindow` flag' or 'why we need this flag in `options`' ?
For example we can have **`open(path, pageUrl[, newWindow][, cmdArgs])`**

**Comment by AlexanderMoskovkin** [comment]
Or will we always open a page in the new window?

**Comment by inikulin** [comment]
We always open a page in a new window. 
`
you should learn what cmd argument you should use to open a page in a new window for each browser(-new-window or --new-window) when using this module. 
`

We should keep flags in `testcafe` with the aliases. Moreover user can provide custom flags. I don't think we should perform any browser-specific analyzis in this package. So, we should end up with just `cmd`.

**Comment by AlexanderMoskovkin** [comment]
> We always open a page in a new window. 

If `testcafe-browser-natives` always open a page in a new window you can remove `new-window` flags from `testcafe` aliases, yes?

**Comment by inikulin** [comment]
No

**Comment by inikulin** [comment]
After short personal discussion we came to conslusion to move `installations.js` from the `testcafe` to the `browser-natives`. And add `macOpenCmd` to aliases.
